Local - only available to other code in this scope. A function, for example, only has access to the names defined in that function or passed into the function.

Enclosing - only exists for nested functions. Inner nests can have access to the names in outer nests

Global - available to all your code and can pass through modules, classes, etc.

Built in - all names that are created by Python when you run a script

In [4]:
class a_sample_class:
    #default/basic constructor
    def __init__(self):
        self.var = 0

    #an instance method for printing
    def print_vars(self):
        print(self.var)

#create instance of class
obj = a_sample_class()

#call instance method to get value for var
obj.print_vars()

0


# Constructors

Constructors get created when you create an instance of a class.

__init__(__ is "dunner")

SELF is a default variable that contains the memory address of the code that we are currently working in.

In [6]:
class a_sample_class:
    class_attr = 5

    def __init__(self, one, two):
        #instance attribute
        self.first = one
        self.second = two

#object is instance of class
obj = a_sample_class(17,42)

#instance attribute as property of object
print(obj.first)

#class attribute as property of object
print(obj.class_attr)

#instance attribute as property of class
print(a_sample_class.first)

#class attribute as property of class
print(a_sample_class.class_attr)

17
5
5


#instance attribute  and class attributes

2 scopes

instance attribute = variable that belongs to a specific instance of instantation.
Defined inside the constructor (init). Can access from the scope of an object (local)

Class attribute = type of variable that belongsto the class itself. Similar to static attributes in Java (not exactly the same). It is both 

In [7]:
help (obj)

Help on a_sample_class in module __main__ object:

class a_sample_class(builtins.object)
 |  a_sample_class(one, two)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, one, two)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  class_attr = 5



In [8]:
#dir = directory of names in a current, local scope
dir()

['In',
 'Out',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'a_sample_class',
 'exit',
 'get_ipython',
 'obj',
 'open',
 'quit']

In [9]:
# returning the current module namespace
# namespace = mapping between objects and current names. These are the defined names,
# and they also include information about the objects each name references.
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'class a_sample_class:\n    #default/basic constructor\n    def__init__(self):\n    self.var = 0\n\n    #an instance method for printing\n    def print_vars(self):\n        print(self.var)\n\n#create instance of class\nobj = a_sample_class()\n\n#call instance method to get value for var\nobj.print_vars()',
  'class a_sample_class:\n    #default/basic constructor\n    def__init__(self)\n    self.var = 0\n\n    #an instance method for printing\n    def print_vars(self):\n        print(self.var)\n\n#create instance of class\nobj = a_sample_class()\n\n#call instance method to get value for var\nobj.print_vars()',
  'class a_sample_class:\n    #default/basic constructor\n    def __init__(self):\n    self.var = 0\n\n 

# Instance, Class, and Static Methods

In [16]:
class Candy:
    #variables that start with a single underscore are reserved for internal purposes
    def _init__(self, _brand, 
                _is_caramel=False, 
                _is_chocolate=False, 
                _is_vegan=False,
                _has_nuts=False,
                _type='chocolate',
                _calories=200):
        self.brand = _brand
        self.is_caramel = _is_caramel
        self.is_chocolate = _is_chocolate
        self.is_vegan = _is_vegan
        self.has_nuts = _has_nuts
        self.calories = _calories
        self.type = _type

    #class method - used to modify the state of the class (for all instances)
    @classmethod
    def snickers(cls):
        return cls('Mars', _is_caramel=True, _is_chocolate=True, _has_nuts=True, _type='Snickers')
    
    #instance method -- can access and modify both the class and instance state 
    #printing is accessing state
    def display(self): 
        print(f'My favorite candy is {self.brand} {self.type}')

    #static method -- used for comparison or validation
    #commonly used in data for checking if data meets particular conditions
    #if you want to check the value without needing an instance of it
    @staticmethod
    def calories (size, n)
    

In [15]:
snickers_bar = Candy.snickers()
snickers_bar.display()

TypeError: Candy() takes no arguments

In [ ]:
Candy.calories('funsized',50)

In [17]:
def the_decorator(func):
    print("decorator is running")
    func()
    print("still running")

def oh_hi():
    print("Hello there!")

hello = the_decorator(oh_hi)

decorator is running
Hello there!
still running


In [ ]:
#Principles of OOP

#Encapsulation - the implementation details are hidden or encapsulated in objects

#Inheritance - child classes can inherit from parent classes and modules

#Polymorphism - objects and names exist in many forms. So, the same attribute or method can exist in multiple classes and mean different things, etc.

#Abstraction - handling a concept rather than the implementation details

NumPy 
1. Array
2. Array Shaping and Transportation
3. Array Math
4. Array Indexing and Slicing
5. Array Broadcasting

NumPy is all about arrays

Arrays
#Structured Lists of Numbers
>Vectors
>Matrices
>Images
>Tensors
>ConvNets

In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print (a.ndim, a.shape, a.dtype)

2 (2, 3) float32


1. Arrays can have any number of dimensions, including a zero (a scalar).
2. Arrays are typed: np.unit8, np.int64, np.float32, np.float64
3. Arrays are dense. Each element of the array exists and has the same type.
4. Arrays are faster than python lists (consume less memory)
5. Can only combine arrays of the same shape!

In [8]:
#1
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[7,8,9]]],dtype=np.float32)
b.ndim
b

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[7., 8., 9.],
        [7., 8., 9.]]], dtype=float32)

In [10]:
#2
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[7,8,9]]], ndmin=6)
c

array([[[[[[1, 2, 3],
           [4, 5, 6]],

          [[7, 8, 9],
           [7, 8, 9]]]]]])

In [11]:
#3

np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
a = np.array ([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a = a.reshape (3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a = a.reshape (2,-1)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [21]:
b = np.arange(10).reshape (5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
b = b.T
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [ ]:
b = b.transpose (

In [23]:
np.sqrt(b)

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ]])